name: CI/CD Automation

on:
  push:
    branches:
      - "**"
  schedule:
    # Run at 6:30 AM and 6:30 PM CST (which is 11:30 UTC and 23:30 UTC)
    - cron: '30 11 * * *'  # 6:30 AM CST
jobs:
  automation:
    if: github.ref_name == 'sandbox' || github.ref_name == 'develop' || github.ref_name == 'production'
    runs-on: ["linux", "self-hosted", "ubuntu", "custom-runner", "docker"]
    steps:
      - name: 🛠 Checkout Repository
        uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: 📦 Install Python Dependencies
        run: |
          pip install -r image-scan/requirements.txt


      - name: 🔢 install trivy
        run: |
          sudo apt-get install zip unzip wget gnupg -y 
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update 
          sudo apt-get install trivy -y 

      - name: 🔢 Run Trivy Image Scan & upload to package registry
        env:
          GIT_CLONE_USER: ${{ secrets.GIT_CLONE_USER }}
          GIT_CLONE_TOKEN: ${{ secrets.GIT_CLONE_TOKEN }}
        run: |
          cd image-scan
          python scan.py
          ls -l 


      - name: 🔢send to package registry
        env:
          GIT_CLONE_USER: ${{ secrets.GIT_CLONE_USER }}
          GIT_CLONE_TOKEN: ${{ secrets.GIT_CLONE_TOKEN }}
        run: |
          cd image-scan
          bash -x package.sh





################## DO NOT TOUCH CODE BELOW IT IS FOR GITLAB MIRROR
      - name: 🌍 SETTING GITLAB MIRROR utility-scripts
        if: github.ref_name == 'sandbox' || github.ref_name == 'develop' || github.ref_name == 'production' 
        env:
          GIT_CLONE_USER: ${{ secrets.GIT_CLONE_USER }}
          GIT_CLONE_TOKEN: ${{ secrets.GIT_CLONE_TOKEN }}
        run: |
            git clone -b develop \
               "https://${GIT_CLONE_USER}:${GIT_CLONE_TOKEN}@git.edusuc.net/WEBFORX/utility-scripts.git" 
            ls -l


      - name: 🌍 SETTING VARIABLE FOR GITLAB MIRROR
        if: github.ref_name == 'sandbox' || github.ref_name == 'develop' || github.ref_name == 'production' 
        run: |
          echo "BRANCH=${GITHUB_REF_NAME}" >> $GITHUB_ENV
          echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV
          echo "Working on branch: ${GITHUB_REF_NAME}"
          echo "Repo: ${GITHUB_REPOSITORY##*/}"

          echo "Working on branch: $BRANCH"
          echo "Repo: ${REPO_NAME}"
          
          
      - name: 🌍 SETTING GITLAB MIRROR
        if: github.ref_name == 'sandbox' || github.ref_name == 'develop' || github.ref_name == 'production' 
        env:
          BRANCH: ${{ env.BRANCH }}
          REPO_NAME: ${{ env.REPO_NAME }}
          GIT_CLONE_USER: ${{ secrets.GIT_CLONE_USER }}
          GIT_CLONE_TOKEN: ${{ secrets.GIT_CLONE_TOKEN }}
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
            bash -x utility-scripts/clone-push.sh 
