#!/usr/bin/env node
// Reads business-info/catalog.json and emits deterministic SQL that populates
// service_groups + services + service_variants for one stylist. Stable IDs
// (sha1-derived UUIDs) so the live DB and seed.sql match and re-runs are idempotent.
//
// Usage:
//   node scripts/build-catalog.mjs [stylistId]        > catalog.sql
// Default stylistId = the owner (QueenG).

import { readFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dir = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dir, "..");
const OWNER = "11111111-1111-1111-1111-111111111111";
const stylistId = process.argv[2] || OWNER;

const catalog = JSON.parse(readFileSync(join(ROOT, "business-info/catalog.json"), "utf8"));

// deterministic UUID v5-ish from a string (namespaced by stylist)
function uid(kind, key) {
  const h = createHash("sha1").update(`${stylistId}:${kind}:${key}`).digest("hex");
  return [h.slice(0, 8), h.slice(8, 12), "5" + h.slice(13, 16), "8" + h.slice(17, 20), h.slice(20, 32)].join("-");
}
const q = (s) => (s === null || s === undefined ? "null" : `'${String(s).replace(/'/g, "''")}'`);

const lines = [];
lines.push(`-- Generated by scripts/build-catalog.mjs for stylist ${stylistId} — DO NOT hand-edit.`);
lines.push(`-- Source of truth: business-info/catalog.json (transcribed from the price-list PDF).`);

for (const g of catalog.groups) {
  const gid = uid("group", g.slug);
  lines.push(
    `insert into service_groups (id, stylist_id, name, slug, kind, description, sort_order, is_active) values ` +
      `(${q(gid)}, ${q(stylistId)}, ${q(g.name)}, ${q(g.slug)}, ${q(g.kind)}, ${q(g.description ?? null)}, ${g.sort}, true);`
  );
  for (const s of g.services) {
    const sid = uid("service", `${g.slug}/${s.name}`);
    const prices = s.variants.map((v) => v.price);
    const basePrice = Math.min(...prices) * 100; // "starting at" reference (cents)
    const dur = Math.min(...s.variants.map((v) => v.durationMin || 180));
    lines.push(
      `insert into services (id, stylist_id, group_id, name, description, category, duration_minutes, buffer_minutes, ` +
        `base_price, deposit_percent, deposit_flat_cents, requires_deposit, tax_rate, is_active, sort_order) values ` +
        `(${q(sid)}, ${q(stylistId)}, ${q(gid)}, ${q(s.name)}, ${q(s.description ?? null)}, ${q(g.name)}, ${dur}, 30, ` +
        `${basePrice}, 50, 5000, true, 0.08250, true, ${s.sort});`
    );
    s.variants.forEach((v, i) => {
      const vid = uid("variant", `${g.slug}/${s.name}/${v.label}/${i}`);
      lines.push(
        `insert into service_variants (id, service_id, stylist_id, size, length, label, price_cents, price_from, duration_minutes, sort_order, is_active) values ` +
          `(${q(vid)}, ${q(sid)}, ${q(stylistId)}, ${q(v.size ?? null)}, ${q(v.length ?? null)}, ${q(v.label)}, ${v.price * 100}, ${v.priceFrom ? "true" : "false"}, ${v.durationMin || 180}, ${i}, true);`
      );
    });
  }
}

process.stdout.write(lines.join("\n") + "\n");
