apiVersion: v1
kind: Secret
metadata:
  name: gitlab-registry-storage
  namespace: gitlab
type: Opaque
stringData:
  config: |
    s3:
      bucket: CHANGE_ME_REGISTRY_BUCKET
      region: us-east-1
      v4auth: true
